### ISSUE TITLE
Cannot login/create account from homepage

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#19] opened 2016-03-14 21:34 UTC
We need a login/create account link in the header.

**Comment by jefftriplett** [comment] 2016-03-14 23:16
![](https://www.evernote.com/l/ABtvxYnJIpFHEoDtBIv7P5P0_mrdAL6l1PkB/image.png)

**Comment by jefftriplett** [comment] 2016-03-14 23:19
This is a duplicate of #10. Closing in favor of just having one.

**Closed by jefftriplett** 2016-03-14 23:19 UTC
Labels: blockers
