### ISSUE TITLE
Talk detail page renders bullets/lists oddly 

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#121] opened 2016-06-14 17:18 UTC
I filed this before, but it looks like that issue was closed. 

When a talk has bullets, or a nested list, it renders really off-center. I think this would be at least partially addressed by left-justifying the "abstract" section. Can we do that? I anticipate this will apply to lots of talks, but one in particular is https://2016.djangocon.us/schedule/presentation/10/ (In admin: https://2016.djangocon.us/admin/symposion_schedule/presentation/10/change/) 

![talkdetail](https://cloud.githubusercontent.com/assets/2286304/16052441/2645fa52-3219-11e6-94f2-b4fe77b3c573.png)

**Comment by jefftriplett** [comment] 2016-06-14 17:50
@brosner we are having the content version problems. When I refresh I see the old information sometimes and other times I see the new.

**Comment by jefftriplett** [comment] 2016-06-14 17:52
@mightym shouldn't we see bullet points?

**Comment by mightym** [comment] 2016-06-14 17:56
I can't reproduce this locally. Removed all horizontal centering. Or is there maybe another template besides `presentation_detail.html` which I overlooked?

**Comment by jefftriplett** [comment] 2016-06-14 18:02
@mightym please ignore the centering. Can you confirm that bullet points work and fix them if they do not?

**Comment by mightym** [comment] 2016-06-14 18:07
Yes I removed all bullet points. Will add them back.

**Comment by jefftriplett** [comment] 2016-06-14 18:47
I can confirm that we now see bullet points. I'm closing since the static issue was submitted to Eldarion via email. Thanks again @mightym

**Closed by jefftriplett** 2016-06-14 18:47 UTC
