### ISSUE TITLE
No error messages show on proposal form 

### ISSUE THREAD

**Issue by williln** [djangocon/2016.djangocon.us#49] opened 2016-03-18 15:36 UTC
When you leave out a required field, like "Title," and click "save," you don't receive an error message. The page just refreshes. When you go to your dashboard, it's clear the page hasn't saved. This could lead people to think their proposals have saved successfully when they have not, because of an error they haven't seen.

**Comment by mightym** [comment] 2016-03-18 22:48
Will try to find a quick solution for this. Related to https://github.com/djangocon/2016.djangocon.us/issues/50#event-595283409

**Comment by jefftriplett** [comment] 2016-03-19 15:35
I'm closing this since it's a duplicate of #50 as @mightym mentioned.

**Closed by jefftriplett** 2016-03-19 15:35 UTC
